import {sanitizeVisual,compileVisualPrompt,normalizedRect,invalidateVisual,drawVisual,getVisualSource,sourceSize,isPanoramaSource,prepareVisualAssets,VISUAL_LIMITS} from './visual-render.mjs';
export const VISUAL_STRINGS={
 vTitle:'Photo motion & design',vIntro:'Local pixel effects and editable vector graphics. This panel does not generate human actions, new clothing, hidden scenery, or photorealistic objects.',
 vPrompt:'Visual effect prompt (separate from narration)',vPromptHint:'Examples: water ripples, sway, rain, snow, zoom in, pan left. For other languages, choose the effect below.',vApply:'Apply supported effects',vRecipe:'Applied recipe',vUnmatched:'No supported effect matched. Choose a listed effect; the photo will otherwise remain unchanged.',vUnsupported:'This prompt includes actions this pixel engine cannot create. Laughing, reading, changing clothes and new scenery require a separate generative workflow.',vMatched:'The selected recipe changes existing pixels. Check the effect and camera controls before export.',
 vEffect:'Pixel effect',vNone:'None',vWater:'Water ripples',vSway:'Gentle sway',vRain:'Rain particles',vSnow:'Snow particles',vStrength:'Effect strength',vRegion:'Effect region',vRegionHint:'Drag a rectangle on the photo with a mouse or one finger. Water and sway affect only this rectangle; the rectangle is not an object segmentation mask.',vRegionReset:'Use lower half',vPhotoOnly:'Pixel effects and panorama viewing require a photo. Vector overlays also work with video.',vNoScene:'Select or add a scene first.',
 vDesign:'Vector design layers',vDesignHint:'Place original vector props or your own transparent PNG. They remain flat overlays; no 3D room geometry, automatic occlusion, clothing replacement or face generation is inferred.',vKind:'Object',vSofa:'Sofa',vPlant:'Plant',vLamp:'Lamp',vBird:'Bird',vFish:'Fish',vImage:'PNG image',vAdd:'Add object',vUpload:'Import transparent PNG',vLayer:'Selected layer',vX:'Horizontal position',vY:'Vertical position',vScale:'Size',vRotation:'Rotation',vOpacity:'Opacity',vColor:'Color',vAnimate:'Animate bird, fish or plant',vFront:'Bring forward',vBack:'Send backward',vRemove:'Delete layer',vMaxLayers:'A scene supports up to 8 layers.',vPNGError:'Use a PNG up to 2 MB. Imported images are resized to at most 512 × 512 pixels; each stored layer is limited to 1.5 MB of text.',vNoLayers:'No design layers yet.',vExportPNG:'Save composed PNG',vWorking:'Preparing image…',vDone:'Saved. The original photo is unchanged.',vImageError:'The image could not be loaded. Try a smaller PNG.',
 vPanorama:'Existing panorama viewer',vPanoramaHint:'Enable only for a genuine 2:1 equirectangular panorama. A normal wide photo is not a 360° capture. This view reveals only pixels already present in the uploaded panorama.',vPanoEnable:'Use this photo as an existing 360° panorama',vPanoInvalid:'This photo is not approximately 2:1. Upload a genuine equirectangular panorama; no missing views are generated.',vYaw:'Viewing direction',vSweep:'Panorama sweep',vPanoPriority:'Panorama viewing takes priority over water, sway, rain and snow effects.',vCanvasLabel:'Photo effect region selector',vLayerStatus:'Layer count',vPreset:'Quick design',vRoom:'Room props',vNature:'Bird and plant',vReplaceHint:'Imported PNG overlays retain their alpha transparency; no background removal is performed.',vSnapshotHint:'PNG export uses this scene’s source aspect ratio and current design at its midpoint, without subtitles.',vSelectAll:'Use whole photo',vBusy:'Finish or cancel the current operation first.'
};
const uid=()=>globalThis.crypto?.randomUUID?.()||`layer-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const create=(tag,properties={})=>Object.assign(document.createElement(tag),properties);
/** t may be t(key,lang) or an already-bound t(key). */
export function mountVisualTools({container,getScene,onChange=()=>{},t,getLanguage=()=> 'en',isBusy=()=>false}){
 if(!container)throw new Error('Visual tools container is required.');
 const refs={},nodes=[],tr=key=>{const value=t?.(key,getLanguage());return typeof value==='string'&&value!==key?value:VISUAL_STRINGS[key]||key};
 let selectedLayer='',lastScene=null,regionDrag=null,localBusy=false,destroyed=false,noticeKey='',updating=false;
 container.classList.add('visual-tools');
 const translated=(tag,key,parent,properties={})=>{const n=create(tag,properties);n.dataset.visualKey=key;n.textContent=tr(key);nodes.push(n);parent.append(n);return n};
 const hint=(key,parent)=>translated('p',key,parent,{className:'visual-hint'});
 const button=(key,parent,fn)=>{const b=translated('button',key,parent,{type:'button'});b.addEventListener('click',fn);return b};
 const field=(key,parent,input)=>{const label=create('label',{className:'visual-field'});translated('span',key,label);label.append(input);parent.append(label);return input};
 const select=(key,parent,items)=>{const e=create('select');for(const[value,label]of items){const o=create('option',{value});o.dataset.visualKey=label;o.textContent=tr(label);nodes.push(o);e.append(o)}return field(key,parent,e)};
 const range=(key,parent,min,max,step)=>{const label=create('label',{className:'visual-field'});const line=create('span',{className:'visual-label-line'});translated('span',key,line);const output=create('output');line.append(output);label.append(line);const input=create('input',{type:'range',min:String(min),max:String(max),step:String(step)});label.append(input);parent.append(label);input.addEventListener('input',()=>{output.value=input.value});return{input,output}};
 const section=(key)=>{const details=create('details');translated('summary',key,details);const body=create('div',{className:'visual-section'});details.append(body);container.append(details);return{details,body}};
 translated('h3','vTitle',container);hint('vIntro',container);
 refs.empty=hint('vNoScene',container);
 refs.prompt=field('vPrompt',container,create('textarea',{rows:2,maxLength:1200}));hint('vPromptHint',container);
 const promptActions=create('div',{className:'visual-buttons'});container.append(promptActions);refs.apply=button('vApply',promptActions,applyPrompt);
 refs.notice=create('p',{className:'visual-notice',role:'status'});container.append(refs.notice);
 refs.recipe=create('p',{className:'visual-recipe'});container.append(refs.recipe);
 refs.effect=select('vEffect',container,[['none','vNone'],['water','vWater'],['sway','vSway'],['rain','vRain'],['snow','vSnow']]);
 refs.strength=range('vStrength',container,0,1,.05);
 refs.regionBox=create('div',{className:'visual-region-box'});translated('h4','vRegion',refs.regionBox);hint('vRegionHint',refs.regionBox);
 refs.canvas=create('canvas',{width:400,height:225,className:'visual-region-canvas'});refs.canvas.setAttribute('aria-label',tr('vCanvasLabel'));refs.regionBox.append(refs.canvas);
 const regionButtons=create('div',{className:'visual-buttons'});refs.regionBox.append(regionButtons);button('vRegionReset',regionButtons,()=>setRegion({x:0,y:.5,width:1,height:.5}));button('vSelectAll',regionButtons,()=>setRegion({x:0,y:0,width:1,height:1}));container.append(refs.regionBox);
 const design=section('vDesign');refs.design=design;hint('vDesignHint',design.body);
 const quick=create('div',{className:'visual-buttons'});design.body.append(quick);button('vRoom',quick,()=>addPreset('room'));button('vNature',quick,()=>addPreset('nature'));
 refs.kind=select('vKind',design.body,[['sofa','vSofa'],['plant','vPlant'],['lamp','vLamp'],['bird','vBird'],['fish','vFish']]);
 const addButtons=create('div',{className:'visual-buttons'});design.body.append(addButtons);button('vAdd',addButtons,()=>addLayer(refs.kind.value));button('vUpload',addButtons,()=>refs.png.click());
 refs.png=create('input',{type:'file',accept:'image/png',hidden:true});refs.png.style.display='none';refs.png.addEventListener('change',importPNG);design.body.append(refs.png);hint('vReplaceHint',design.body);
 refs.layers=field('vLayer',design.body,create('select'));refs.count=create('p',{className:'visual-hint'});design.body.append(refs.count);
 refs.controls=create('div');design.body.append(refs.controls);
 refs.x=range('vX',refs.controls,0,1,.01);refs.y=range('vY',refs.controls,0,1,.01);refs.scale=range('vScale',refs.controls,.05,1.5,.01);refs.rotation=range('vRotation',refs.controls,-180,180,1);refs.opacity=range('vOpacity',refs.controls,.05,1,.05);
 refs.color=field('vColor',refs.controls,create('input',{type:'color'}));
 const animateLabel=create('label',{className:'visual-check'});refs.animate=create('input',{type:'checkbox'});animateLabel.append(refs.animate);translated('span','vAnimate',animateLabel);refs.controls.append(animateLabel);
 const stack=create('div',{className:'visual-buttons'});refs.controls.append(stack);button('vBack',stack,()=>moveLayer(-1));button('vFront',stack,()=>moveLayer(1));button('vRemove',stack,deleteLayer);
 refs.snapshot=button('vExportPNG',design.body,exportPNG);hint('vSnapshotHint',design.body);
 const pano=section('vPanorama');hint('vPanoramaHint',pano.body);const panoLabel=create('label',{className:'visual-check'});refs.pano=create('input',{type:'checkbox'});panoLabel.append(refs.pano);translated('span','vPanoEnable',panoLabel);pano.body.append(panoLabel);
 refs.yaw=range('vYaw',pano.body,-180,180,1);refs.sweep=range('vSweep',pano.body,0,180,5);hint('vPanoPriority',pano.body);
 const blocked=()=>destroyed||localBusy||isBusy()||!getScene();
 const current=()=>{const s=getScene();if(s&&!s.visual)s.visual=sanitizeVisual();return s};
 function changed(reason){const s=current();if(!s)return;invalidateVisual(s);onChange({scene:s,reason});updateRecipe();}
 function tell(key){noticeKey=key;refs.notice.textContent=key?tr(key):'';refs.notice.hidden=!key;}
 function applyPrompt(){if(blocked())return;const s=current(),r=compileVisualPrompt(refs.prompt.value,s.objects||[]);s.visual.prompt=refs.prompt.value;s.visual.effect=r.effect;if(r.camera)s.motion=r.camera;tell(r.unsupported?'vUnsupported':r.matched?'vMatched':'vUnmatched');changed('prompt');refresh()}
 function setRegion(rect){if(blocked())return;current().visual.region=normalizedRect(rect);changed('region');paintRegion();}
 function updateRecipe(){const s=current();if(!s)return;const key={none:'vNone',water:'vWater',sway:'vSway',rain:'vRain',snow:'vSnow'}[s.visual.effect]||'vNone';refs.recipe.textContent=`${tr('vRecipe')}: ${s.visual.panorama?tr('vPanorama'):tr(key)+' · '+Math.round(s.visual.strength*100)+'%'}`;}
 function mutate(field,value){if(blocked())return;current().visual[field]=value;tell('');changed(field);if(field==='effect'||field==='panorama')refresh();}
 refs.prompt.addEventListener('input',()=>{if(blocked())return;current().visual.prompt=refs.prompt.value;});
 refs.effect.addEventListener('change',()=>mutate('effect',refs.effect.value));refs.strength.input.addEventListener('input',()=>mutate('strength',Number(refs.strength.input.value)));
 refs.pano.addEventListener('change',()=>{const s=current();if(!s||blocked())return;if(refs.pano.checked&&!isPanoramaSource(s)){refs.pano.checked=false;tell('vPanoInvalid');return}mutate('panorama',refs.pano.checked)});
 refs.yaw.input.addEventListener('input',()=>mutate('yaw',Number(refs.yaw.input.value)));refs.sweep.input.addEventListener('input',()=>mutate('sweep',Number(refs.sweep.input.value)));
 function layer(){return current()?.visual.layers.find(l=>l.id===selectedLayer)}
 function addLayer(kind,extra={}){if(blocked())return;const s=current();if(s.visual.layers.length>=VISUAL_LIMITS.layers){tell('vMaxLayers');return}const item={id:uid(),kind,x:.5,y:.65,scale:.4,rotation:0,opacity:1,color:'#79cdbc',animate:false,...extra};s.visual.layers.push(item);selectedLayer=item.id;tell('');changed('add-layer');refresh()}
 function addPreset(kind){if(blocked())return;const s=current(),count=kind==='room'?3:2;if(s.visual.layers.length+count>VISUAL_LIMITS.layers){tell('vMaxLayers');return}
  if(kind==='room'){addLayer('sofa',{x:.48,y:.72,scale:.62});addLayer('plant',{x:.82,y:.66,scale:.42,color:'#528956'});addLayer('lamp',{x:.2,y:.62,scale:.55,color:'#efd6a5'})}
  else{addLayer('bird',{x:.6,y:.23,scale:.15,animate:true,color:'#edf6ef'});addLayer('plant',{x:.83,y:.72,scale:.38,color:'#5ba57b'})}}
 function updateLayer(field,value){if(blocked()||!layer())return;layer()[field]=value;changed('layer-'+field)}
 for(const name of['x','y','scale','rotation','opacity'])refs[name].input.addEventListener('input',()=>updateLayer(name,Number(refs[name].input.value)));
 refs.color.addEventListener('input',()=>updateLayer('color',refs.color.value));refs.animate.addEventListener('change',()=>updateLayer('animate',refs.animate.checked));refs.layers.addEventListener('change',()=>{selectedLayer=refs.layers.value;refresh()});
 function moveLayer(delta){if(blocked())return;const s=current(),at=s.visual.layers.findIndex(l=>l.id===selectedLayer),to=at+delta;if(at<0||to<0||to>=s.visual.layers.length)return;const[l]=s.visual.layers.splice(at,1);s.visual.layers.splice(to,0,l);changed('layer-order');refresh()}
 function deleteLayer(){if(blocked())return;const s=current();s.visual.layers=s.visual.layers.filter(l=>l.id!==selectedLayer);selectedLayer=s.visual.layers.at(-1)?.id||'';changed('delete-layer');refresh()}
 function point(e){const box=refs.canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-box.left)/box.width)),y:Math.max(0,Math.min(1,(e.clientY-box.top)/box.height))}}
 refs.canvas.addEventListener('pointerdown',e=>{if(blocked()||getScene().mediaType==='video'||e.button>0)return;regionDrag={pointer:e.pointerId,start:point(e),end:point(e)};refs.canvas.setPointerCapture(e.pointerId);e.preventDefault();paintRegion()});
 refs.canvas.addEventListener('pointermove',e=>{if(regionDrag?.pointer!==e.pointerId)return;regionDrag.end=point(e);paintRegion()});
 refs.canvas.addEventListener('pointerup',e=>{if(regionDrag?.pointer!==e.pointerId)return;regionDrag.end=point(e);const a=regionDrag.start,b=regionDrag.end;regionDrag=null;setRegion({x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),width:Math.max(.025,Math.abs(a.x-b.x)),height:Math.max(.025,Math.abs(a.y-b.y))});if(refs.canvas.hasPointerCapture(e.pointerId))refs.canvas.releasePointerCapture(e.pointerId)});
 refs.canvas.addEventListener('pointercancel',()=>{regionDrag=null;paintRegion()});
 function paintRegion(){const s=current(),c=refs.canvas,ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);if(!s?.image)return;const d=sourceSize(s.image),ratio=d.width/d.height;c.width=400;c.height=Math.max(80,Math.min(600,Math.round(400/ratio)));ctx.drawImage(s.image,0,0,c.width,c.height);let r=s.visual.region;if(regionDrag){const a=regionDrag.start,b=regionDrag.end;r={x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),width:Math.abs(a.x-b.x),height:Math.abs(a.y-b.y)}}ctx.fillStyle='rgba(111,235,202,.16)';ctx.fillRect(r.x*c.width,r.y*c.height,r.width*c.width,r.height*c.height);ctx.strokeStyle='#9bffe0';ctx.lineWidth=2;ctx.setLineDash([5,3]);ctx.strokeRect(r.x*c.width,r.y*c.height,r.width*c.width,r.height*c.height);}
 async function importPNG(){const file=refs.png.files?.[0];refs.png.value='';if(!file||blocked())return;const s=current();if(s.visual.layers.length>=VISUAL_LIMITS.layers){tell('vMaxLayers');return}if(file.type!=='image/png'||file.size>VISUAL_LIMITS.maxPNGBytes){tell('vPNGError');return}localBusy=true;tell('vWorking');refresh();let url='';try{url=URL.createObjectURL(file);const img=new Image();img.src=url;await img.decode();if(img.naturalWidth*img.naturalHeight>25000000)throw new Error('size');const ratio=Math.min(1,512/img.naturalWidth,512/img.naturalHeight),c=create('canvas',{width:Math.max(1,Math.round(img.naturalWidth*ratio)),height:Math.max(1,Math.round(img.naturalHeight*ratio))});c.getContext('2d').drawImage(img,0,0,c.width,c.height);const src=c.toDataURL('image/png');if(src.length>VISUAL_LIMITS.layerCharacters||s.visual.layers.reduce((n,l)=>n+(l.src?.length||0),0)+src.length>VISUAL_LIMITS.totalCharacters)throw new Error('size');if(getScene()!==s)return;localBusy=false;addLayer('image',{src,scale:.45});await prepareVisualAssets([s]);changed('image-ready')}catch{tell('vPNGError')}finally{URL.revokeObjectURL(url);localBusy=false;refresh()}}
 async function exportPNG(){if(blocked())return;const s=current();localBusy=true;tell('vWorking');refresh();try{await prepareVisualAssets([s]);const {renderFrame,prepareVideoFrames}=await import('./media.mjs');await prepareVideoFrames([s],(s.duration||5)/2);const dimensions=sourceSize(getVisualSource(s,.5)),ratio=Math.min(1,1280/dimensions.width,1280/dimensions.height),c=create('canvas',{width:Math.max(1,Math.round(dimensions.width*ratio)),height:Math.max(1,Math.round(dimensions.height*ratio))});renderFrame(c.getContext('2d'),{scenes:[s],time:(s.duration||5)/2,width:c.width,height:c.height,settings:{subtitle:false}});const blob=await new Promise(resolve=>c.toBlob(resolve,'image/png'));if(!blob)throw new Error('PNG unavailable');const url=URL.createObjectURL(blob),a=create('a',{href:url,download:'FRAME-design.png'});a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);tell('vDone')}catch{tell('vImageError')}finally{localBusy=false;refresh()}}
 function refresh(){if(destroyed||updating)return;updating=true;try{const s=getScene();if(s!==lastScene){lastScene=s;noticeKey='';selectedLayer=s?.visual?.layers?.at(-1)?.id||'';regionDrag=null;}if(s&&!s.visual)s.visual=sanitizeVisual();for(const n of nodes)n.textContent=tr(n.dataset.visualKey);refs.canvas.setAttribute('aria-label',tr('vCanvasLabel'));refs.empty.hidden=!!s;const noEdit=!s||isBusy()||localBusy;container.querySelectorAll('input,textarea,select,button').forEach(n=>n.disabled=noEdit);refs.notice.textContent=noticeKey?tr(noticeKey):'';refs.notice.hidden=!noticeKey;if(!s){refs.canvas.getContext('2d').clearRect(0,0,400,600);return}const v=s.visual;if(document.activeElement!==refs.prompt)refs.prompt.value=v.prompt||'';refs.effect.value=v.effect;refs.strength.input.value=v.strength;refs.strength.output.value=Number(v.strength).toFixed(2);refs.pano.checked=v.panorama;for(const k of['yaw','sweep']){refs[k].input.value=v[k];refs[k].output.value=String(v[k])}const photo=s.mediaType!=='video';refs.effect.disabled=noEdit||!photo;refs.strength.input.disabled=noEdit||!photo;refs.pano.disabled=noEdit||!photo;refs.regionBox.hidden=!photo||!['water','sway'].includes(v.effect)||v.panorama;refs.layers.replaceChildren();for(const[lidx,l]of v.layers.entries()){const k={sofa:'vSofa',plant:'vPlant',lamp:'vLamp',bird:'vBird',fish:'vFish',image:'vImage'}[l.kind];refs.layers.add(create('option',{value:l.id,textContent:`${lidx+1}. ${tr(k)}`}))}if(!v.layers.some(l=>l.id===selectedLayer))selectedLayer=v.layers.at(-1)?.id||'';refs.layers.value=selectedLayer;refs.count.textContent=v.layers.length?`${tr('vLayerStatus')}: ${v.layers.length}/8`:tr('vNoLayers');const l=layer();refs.controls.hidden=!l;if(l){for(const k of['x','y','scale','rotation','opacity']){refs[k].input.value=l[k];refs[k].output.value=String(l[k])}refs.color.value=l.color;refs.animate.checked=l.animate;refs.animate.disabled=noEdit||!['plant','bird','fish'].includes(l.kind);refs.color.disabled=noEdit||l.kind==='image'}updateRecipe();paintRegion();}finally{updating=false}}
 refresh();return{refresh,destroy(){destroyed=true;container.replaceChildren()},get busy(){return localBusy}};
}
