import {mountAdvancedUI} from './advanced-ui.mjs';
import {mountExpertUI} from './expert-ui.mjs';
import {mountVisualTools} from './visual-tools.mjs';
import {sanitizeVisual,prepareVisualAssets} from './visual-render.mjs';
import {languages,selectLanguage,t} from './i18n.mjs';
import {renderFrame,totalDuration,locateScene,exportVideo,wavBlob,subtitles,fitAudioDurations,prepareVideoFrames,getExportCapabilities} from './media.mjs';
import {loadDetector,detectImage,disposeDetector} from '../edge/detector-client.mjs';
const $=id=>document.getElementById(id);let expertUI=null,visualUI=null,advancedUI=null;const fileMode=location.protocol==='file:';let lang=selectLanguage(navigator.languages||navigator.language),scenes=[],selected=-1,time=0,playing=false,raf=0,lastClock=0,busy=false,abort=null,ai=null,voices=[],audioContext=null,musicBuffer=null,musicFileName='',recording=null,recordingChunks=[],resultUrl=null,previewSources=[],previewAudioOrigin=0;
const smallDevice=matchMedia('(max-width:700px)').matches||(navigator.deviceMemory&&navigator.deviceMemory<=4);const maxScenes=20,maxFile=(smallDevice?20:50)*1024*1024,maxProject=150*1024*1024;const objectUrls=new Set();const uid=()=>globalThis.crypto?.randomUUID?.()||Math.random().toString(36).slice(2);const message=(zh,en)=>lang.startsWith('zh')?zh:en;const fmt=v=>`${String(Math.floor(v/60)).padStart(2,'0')}:${String(Math.floor(v%60)).padStart(2,'0')}`;
const elements=['sceneName','duration','narration','subtitle','motion','transition','brightness','contrast','saturation','warmth','trimStart','trimEnd'];
function tr(k,vars){return t(k,lang,vars)}
function status(text,progress=0){$('status').textContent=text;$('progressBar').value=Math.min(1,Math.max(0,progress));$('progressLabel').textContent=progress>0?`${Math.round(progress*100)}%`:'';}
function fail(error){if(error?.name==='AbortError')status(tr('cancel'));else status(`${tr('error')}: ${error?.message||error}\n${tr('retry')}`);console.warn(error);}
function clearResult(){if(resultUrl){URL.revokeObjectURL(resultUrl);resultUrl=null}$('resultVideo').removeAttribute('src');$('result').style.display='none';}
async function task(label,fn){if(busy||visualUI?.busy)return;if(recording?.recorder?.state==='recording'){status(message('請先停止錄音，再執行這個操作。','Stop microphone recording before starting another operation.'));return}pause();clearResult();busy=true;abort=new AbortController();$('cancelBtn').disabled=false;$('stateLabel').textContent=label;document.querySelectorAll('button:not(#cancelBtn),input,textarea,select').forEach(e=>e.disabled=true);try{await fn(abort.signal)}catch(e){fail(e)}finally{busy=false;abort=null;$('cancelBtn').disabled=true;document.querySelectorAll('button:not(#cancelBtn),input,textarea,select').forEach(e=>e.disabled=false);$('stateLabel').textContent=tr('ready');updateEditor();}}
function applyLanguage(){document.documentElement.lang=lang;document.documentElement.dir=languages.find(l=>l.code===lang)?.dir||'ltr';document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=tr(e.dataset.i18n));$('language').value=lang;$('playBtn').textContent=tr(playing?'pause':'play');$('recordBtn').textContent=tr(recording?'stopRecording':'recordVoice');updateList();updateEditor();updateVoiceInfo();populateSystemVoices();$('originalAudioLabel').textContent=tr('originalAudioLabel');expertUI?.refresh();visualUI?.refresh();advancedUI?.refresh();if(fileMode){$('modeInfo').textContent=tr('fileMode');$('fileAiHint').textContent=tr('fileAiHint');}}
$('language').replaceChildren(...languages.map(l=>{const o=new Option(l.label,l.code);return o}));$('language').onchange=()=>{lang=$('language').value;try{localStorage.setItem('frame-story-language',lang)}catch{}applyLanguage()};
function scene(){return scenes[selected]||null}
function settings(){const h=Number($('resolution').value),aspect=$('aspect').value;return{width:aspect==='portrait'?Math.round(h*9/16):aspect==='square'?h:Math.round(h*16/9),height:h,fps:Number($('fps').value),subtitle:$('captions').checked,subtitleSize:Math.max(18,Math.round(h/20)),subtitleColor:'#ffffff',background:'#101418',musicVolume:Number($('musicVolume').value),narrationVolume:1,fadeAudio:true,fitNarration:$('audioFit').checked,format:$('format').value,originalAudio:$('originalAudio').checked,fontFamily:lang.startsWith('zh')?'"FRAME CJK", system-ui, sans-serif':'system-ui, "FRAME CJK", sans-serif'};}
function updateList(){const list=$('sceneList'),timeline=$('timeline');list.replaceChildren();timeline.replaceChildren();scenes.forEach((s,i)=>{const button=document.createElement('button');button.className='scene-item'+(i===selected?' active':'');const img=document.createElement('img');img.src=s.thumbnail||s.image?.src||'';img.alt='';const div=document.createElement('div');const strong=document.createElement('strong');strong.textContent=`${i+1}. ${s.name}`;const small=document.createElement('small');small.textContent=`${s.duration.toFixed(1)} s · ${s.mediaType==='video'?'VIDEO':'PHOTO'}${s.audio?' · ♪':''}`;div.append(strong,small);button.append(img,div);button.onclick=()=>select(i);list.append(button);const block=document.createElement('button');block.className='timeline-block'+(i===selected?' active':'');block.style.width=`${Math.max(80,Math.min(155,s.duration*12))}px`;block.append(document.createTextNode(`${i+1}. ${s.name}`));const sub=document.createElement('small');sub.textContent=`${s.duration.toFixed(1)}s`;block.append(sub);block.onclick=()=>select(i);timeline.append(block)});$('sceneCount').textContent=`${scenes.length} / ${maxScenes}`;const length=totalDuration(scenes);$('totalTime').textContent=fmt(length);$('scrubber').max=String(length||1);time=Math.min(time,length);$('emptyLabel').classList.toggle('hidden',scenes.length>0);draw();}
function select(i){pause();selected=i;time=scenes.slice(0,i).reduce((n,s)=>n+s.duration,0);updateList();updateEditor();drawAsync();}
function updateEditor(){const s=scene();$('selectedNumber').textContent=s?`${selected+1}/${scenes.length}`:'';elements.forEach(id=>{const e=$(id);e.disabled=!s||busy;e.value=s?.[id==='sceneName'?'name':id]??(id==='duration'?5:'')});for(const id of ['brightness','contrast','saturation','warmth'])$(id+'Value').textContent=Number(s?.[id]??(id==='warmth'?0:1)).toFixed(2);$('trimFields').classList.toggle('hidden',s?.mediaType!=='video');$('objects').textContent=s?.objects?.map(o=>`${o.label} (${Math.round(o.score*100)}%)`).join(' · ')||'';$('audioState').textContent=s?.audio?`${tr('audioReady')} · ${s.audio.duration.toFixed(1)} s${s.audioSource?' · '+s.audioSource:''}`:'';for(const id of ['deleteBtn','duplicateBtn','prevScene','nextScene','detectBtn','storyBtn','voiceBtn','voiceUploadBtn','recordBtn'])$(id).disabled=!s||busy;for(const id of ['playVoice','downloadVoice'])$(id).disabled=!s?.audio||busy;$('exportBtn').disabled=!scenes.length||busy;$('playBtn').disabled=!scenes.length||busy;if(fileMode){for(const id of ['detectBtn','storyBtn','voiceBtn','offlineBtn','clearCacheBtn'])$(id).disabled=true;}expertUI?.refresh();visualUI?.refresh();advancedUI?.refresh();}
for(const id of elements){$(id).addEventListener('input',()=>{const s=scene();if(!s)return;const field=id==='sceneName'?'name':id;const old=s[field];s[field]=['duration','brightness','contrast','saturation','warmth','trimStart','trimEnd'].includes(id)?Number($(id).value):$(id).value;if(id==='duration')s.duration=Math.max(1,Math.min(120,s.duration||5));if(id==='narration'&&(!s.subtitle||s.subtitle===old)){s.subtitle=s.narration;$('subtitle').value=s.subtitle}if(id==='trimStart'||id==='trimEnd'){s.trimStart=Math.max(0,Math.min(s.video.duration-.1,Number(s.trimStart)||0));s.trimEnd=Math.min(s.video.duration,Math.max(s.trimStart+.1,Number(s.trimEnd)||s.video.duration));s.duration=Math.min(120,s.trimEnd-s.trimStart);$('duration').value=s.duration.toFixed(1);if(s.originalAudio&&s.audioSource==='VIDEO')s.audio=sliceAudio(s.originalAudio,s.trimStart,s.trimEnd);}if(['brightness','contrast','saturation','warmth'].includes(id))$(id+'Value').textContent=s[id].toFixed(2);updateList();drawAsync();})}
function draw(){const config=settings();const canvas=$('previewCanvas');if(canvas.width!==config.width||canvas.height!==config.height){canvas.width=config.width;canvas.height=config.height}renderFrame(canvas.getContext('2d'),{scenes,time,width:config.width,height:config.height,settings:config});$('scrubber').value=String(time);$('timeLabel').textContent=`${fmt(time)} / ${fmt(totalDuration(scenes))}`;}
let drawing=false;async function drawAsync(){if(drawing)return;drawing=true;try{await prepareVideoFrames(scenes,time);draw()}catch(e){console.warn(e)}finally{drawing=false}}
$('scrubber').oninput=()=>{pause();time=Number($('scrubber').value);drawAsync()};for(const id of ['resolution','aspect','fps','captions'])$(id).onchange=draw;
function stopPreviewAudio(){for(const n of previewSources){try{n.stop()}catch{}}previewSources=[];}
function pause(){playing=false;cancelAnimationFrame(raf);stopPreviewAudio();$('playBtn').textContent=tr('play');}
function audioCtx(){if(!audioContext){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw new Error(tr('unavailable')+': Web Audio');audioContext=new AC()}return audioContext}
function monoBuffer(samples,sampleRate){const c=audioCtx(),b=c.createBuffer(1,samples.length,sampleRate);b.copyToChannel(samples,0);return b}
function sliceAudio(b,start,end){const from=Math.min(b.length,Math.max(0,Math.floor(start*b.sampleRate))),to=Math.min(b.length,Math.max(from+1,Math.floor(end*b.sampleRate))),out=audioCtx().createBuffer(b.numberOfChannels,to-from,b.sampleRate);for(let c=0;c<b.numberOfChannels;c++)out.copyToChannel(b.getChannelData(c).slice(from,to),c);return out}
function schedulePreview(){const c=audioCtx();c.resume();previewAudioOrigin=c.currentTime;let cursor=0;for(const s of scenes){if(s.audio&&(s.audioSource!=='VIDEO'||$('originalAudio').checked)&&cursor+s.audio.duration>time){const start=Math.max(0,cursor-time),offset=Math.max(0,time-cursor),available=Math.min(s.duration-offset,s.audio.duration-offset);if(available>0){const source=c.createBufferSource(),gain=c.createGain();source.buffer=s.audio;gain.gain.value=1;source.connect(gain).connect(c.destination);source.start(c.currentTime+start,offset,available);previewSources.push(source)}}if($('originalAudio').checked&&s.originalAudio&&s.audioSource!=='VIDEO'){const b=sliceAudio(s.originalAudio,s.trimStart,s.trimEnd??s.originalAudio.duration),start=Math.max(0,cursor-time),offset=Math.max(0,time-cursor),available=Math.min(s.duration-offset,b.duration-offset);if(available>0){const source=c.createBufferSource(),gain=c.createGain();source.buffer=b;gain.gain.value=.35;source.connect(gain).connect(c.destination);source.start(c.currentTime+start,offset,available);previewSources.push(source)}}cursor+=s.duration}const mb=getMusicBuffer();if(mb){const source=c.createBufferSource(),gain=c.createGain();source.buffer=mb;source.loop=true;gain.gain.value=Number($('musicVolume').value);source.connect(gain).connect(c.destination);source.start(c.currentTime, time%mb.duration);previewSources.push(source)}}
$('playBtn').onclick=()=>{if(playing){pause();return}if(!scenes.length)return;if(time>=totalDuration(scenes)-.05)time=0;playing=true;lastClock=performance.now();$('playBtn').textContent=tr('pause');try{schedulePreview()}catch(e){status(message('此預覽沒有音訊：','Preview without audio: ')+e.message)}const tick=now=>{if(!playing)return;time=Math.min(totalDuration(scenes),time+(now-lastClock)/1000);lastClock=now;drawAsync();if(time>=totalDuration(scenes)){pause();return}raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick)};
async function dataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}
async function imageFrom(src){const img=new Image();img.decoding='async';img.src=src;await img.decode();return img}
async function videoFrom(src){return new Promise((resolve,reject)=>{const video=document.createElement('video');video.playsInline=true;video.muted=true;video.preload='auto';video.onloadeddata=()=>resolve(video);video.onerror=()=>reject(new Error('Unsupported video codec'));video.src=src;video.load()})}
function baseScene(name){return{id:uid(),name,mediaType:'image',duration:5,narration:'',subtitle:'',motion:'zoom-in',transition:'fade',transitionDuration:.5,brightness:1,contrast:1,saturation:1,warmth:0,trimStart:0,trimEnd:null,objects:[],audio:null,audioSource:''}}
async function addFile(file){if(scenes.length>=maxScenes)throw new Error(tr('maxScenes'));if(file.size>maxFile)throw new Error(`${file.name}: ${message('單一素材限制50MB，請先壓縮。','Each asset is limited to 50 MB. Compress this file first.')}`);const used=scenes.reduce((n,s)=>n+(s.mediaData?.length||0)*.75,0);if(used+file.size>(smallDevice?32:150)*1024*1024)throw new Error(message('素材總量已接近此裝置的保守限制，請減少／壓縮素材或分成較短專案。','Assets exceed the conservative device budget. Compress media or split into shorter projects.'));const src=await dataUrl(file);const s=baseScene(file.name.replace(/\.[^.]+$/,''));s.mediaData=src;const video=/^video\//.test(file.type)||/\.(mp4|mov|webm|m4v)$/i.test(file.name);if(video){s.video=await videoFrom(src);if(!Number.isFinite(s.video.duration)||s.video.duration<=0)throw new Error('Invalid video duration');s.mediaType='video';s.duration=Math.max(1,Math.min(120,s.video.duration));s.trimEnd=s.duration;const c=document.createElement('canvas');c.width=240;c.height=Math.max(1,Math.round(240*s.video.videoHeight/s.video.videoWidth));c.getContext('2d').drawImage(s.video,0,0,c.width,c.height);s.thumbnail=c.toDataURL('image/jpeg',.7);try{s.originalAudio=await audioCtx().decodeAudioData(await file.arrayBuffer());s.audio=sliceAudio(s.originalAudio,0,s.trimEnd);s.audioSource='VIDEO'}catch{$('originalAudioHint').textContent=message('部分影片原音無法解碼，請將音軌另匯入為旁白或配樂。','Some original video audio could not be decoded; import its audio track separately.')}}else{s.image=await imageFrom(src);const maxSide=smallDevice?1280:2048;if(Math.max(s.image.naturalWidth,s.image.naturalHeight)>maxSide){const scale=maxSide/Math.max(s.image.naturalWidth,s.image.naturalHeight),c=document.createElement('canvas');c.width=Math.round(s.image.naturalWidth*scale);c.height=Math.round(s.image.naturalHeight*scale);c.getContext('2d').drawImage(s.image,0,0,c.width,c.height);s.mediaData=c.toDataURL('image/jpeg',.9);s.image=await imageFrom(s.mediaData)}const pixelBudget=smallDevice?12000000:40000000;if(s.image.naturalWidth*s.image.naturalHeight+scenes.reduce((n,row)=>n+(row.image?row.image.naturalWidth*row.image.naturalHeight:0),0)>pixelBudget)throw new Error(message('照片工作副本總像素超過裝置保守限制，請減少分鏡。','Working photos exceed the conservative pixel budget. Use fewer scenes.'));const c=document.createElement('canvas');c.width=180;c.height=100;const aspect=s.image.naturalWidth/s.image.naturalHeight;c.getContext('2d').drawImage(s.image,0,0,180,180/aspect);s.thumbnail=c.toDataURL('image/jpeg',.7)}scenes.push(s);selected=scenes.length-1}
async function loadFiles(files){if(busy)return;pause();let problems=[];for(const file of files){try{await addFile(file)}catch(e){problems.push(e.message)}}select(Math.max(0,selected));if(problems.length)status(problems.join('\n'));else status(message('素材已在本機讀取，未上傳。','Assets loaded on this device; nothing uploaded.'))}
$('addBtn').onclick=()=>$('mediaInput').click();$('mediaInput').onchange=async()=>{await loadFiles($('mediaInput').files);$('mediaInput').value=''};$('dropzone').ondragover=e=>{e.preventDefault();$('dropzone').classList.add('dragover')};$('dropzone').ondragleave=()=>$('dropzone').classList.remove('dragover');$('dropzone').ondrop=e=>{e.preventDefault();$('dropzone').classList.remove('dragover');loadFiles(e.dataTransfer.files)};
function move(delta){const target=selected+delta;if(target<0||target>=scenes.length)return;const s=scenes.splice(selected,1)[0];scenes.splice(target,0,s);select(target)}$('prevScene').onclick=()=>move(-1);$('nextScene').onclick=()=>move(1);$('deleteBtn').onclick=()=>{pause();const old=scenes.splice(selected,1)[0];old?.video?.pause();selected=Math.min(selected,scenes.length-1);updateList();updateEditor()};$('duplicateBtn').onclick=async()=>{const s=scene();if(!s||scenes.length>=maxScenes)return;try{const duplicate={...s,id:uid(),name:s.name+' · 2',objects:[...s.objects],visual:sanitizeVisual(s.visual)};if(s.mediaType==='video')duplicate.video=await videoFrom(s.mediaData);scenes.splice(selected+1,0,duplicate);select(selected+1)}catch(e){fail(e)}};
async function detect(s,signal){if(s.mediaType!=='image')throw new Error(message('物件辨識目前使用照片，影片請先擷取一張圖片。','Detection accepts photos. Extract a frame from the video first.'));status(message('正在載入本機 CPU 物件模型…','Loading the local CPU object detector…'),.1);await loadDetector({workerUrl:new URL('edge/detector-worker.js',document.baseURI),modelUrl:new URL('edge/model/coco-ssd-lite/model.json',document.baseURI).href,signal,onProgress:p=>status('COCO-SSD CPU: '+p.stage,p.progress*.4)});const c=document.createElement('canvas'),scale=Math.min(1,640/Math.max(s.image.naturalWidth,s.image.naturalHeight));c.width=Math.round(s.image.naturalWidth*scale);c.height=Math.round(s.image.naturalHeight*scale);c.getContext('2d').drawImage(s.image,0,0,c.width,c.height);s.objects=await detectImage(c.getContext('2d').getImageData(0,0,c.width,c.height),{signal,maxObjects:8});status(s.objects.length?s.objects.map(o=>`${o.label} ${Math.round(o.score*100)}%`).join(', '):message('未辨識到常見物件。可自行描述場景。','No common objects detected. Describe the scene yourself.'),1);updateEditor()}
$('detectBtn').onclick=()=>task(tr('detect'),signal=>detect(scene(),signal));
async function getAi(){if(!ai){ai=await import('./ai/client.mjs');voices=await ai.voiceCatalog();populateVoices()}return ai}
$('storyBtn').onclick=()=>task(tr('generateStory'),async signal=>{const s=scene(),model=await getAi();if(!s.objects.length&&s.mediaType==='image')await detect(s,signal);disposeDetector();const text=await model.generateNarration({prompt:s.narration||s.name,objects:s.objects,language:'en',maxTokens:95,signal,onProgress:p=>status(typeof p==='string'?p:JSON.stringify(p),p?.total?p.loaded/p.total:typeof p?.progress==='number'?p.progress/100:.3)});s.narration=text;s.subtitle=text;updateEditor();status(message('AI草稿已加入，請核對文字再配音。','AI draft added. Review the story before generating speech.'),1)});
function populateVoices(){const oldLang=$('voiceLanguage').value,oldVoice=$('voice').value;const codes=[...new Set(voices.map(v=>v.language))];$('voiceLanguage').replaceChildren(...codes.map(code=>new Option(languages.find(l=>l.code===code||l.code.split('-')[0]===code.split('-')[0])?.label||code,code)));const preferred=codes.find(c=>c===oldLang)||codes.find(c=>c.split('-')[0]===lang.split('-')[0])||codes[0];$('voiceLanguage').value=preferred||'';const subset=voices.filter(v=>v.language===preferred);$('voice').replaceChildren(...subset.map(v=>new Option(v.name,v.id)));if(subset.some(v=>v.id===oldVoice))$('voice').value=oldVoice;updateVoiceInfo()}
function updateVoiceInfo(){const v=voices.find(v=>v.id===$('voice').value);$('voiceInfo').textContent=v?`${v.description||v.name}${v.language?' · '+v.language:''}`:message('神經聲庫正在載入。','Loading neural voice catalog.');$('rateValue').textContent=Number($('voiceRate').value).toFixed(2)+'×'}$('voiceLanguage').onchange=()=>{const code=$('voiceLanguage').value;$('voice').replaceChildren(...voices.filter(v=>v.language===code).map(v=>new Option(v.name,v.id)));updateVoiceInfo()};$('voice').onchange=updateVoiceInfo;$('voiceRate').oninput=updateVoiceInfo;
$('voiceBtn').onclick=()=>task(tr('generateVoice'),async signal=>{const s=scene();if(!s.narration.trim())throw new Error(message('請先輸入旁白文字。','Enter narration text first.'));const model=await getAi();status(message('CPU 正在生成音訊；首次載入可能需要一段時間。','Generating audio on the CPU. Initial model loading may take time.'),.05);const result=await model.synthesizeSpeech({text:s.narration,voice:$('voice').value,language:$('voiceLanguage').value,rate:Number($('voiceRate').value),signal,onProgress:p=>status(typeof p==='string'?p:JSON.stringify(p),p?.total?p.loaded/p.total:typeof p?.progress==='number'?p.progress/100:.4)});s.audio=monoBuffer(result.audio,result.sampleRate);s.audioSource='AI';if($('audioFit').checked){s.duration=Math.min(120,Math.max(s.duration,s.audio.duration+.4));if(s.audio.duration>119)status(message('旁白超過120秒單幕限制，請拆成多幕。','Narration exceeds the 120-second scene limit. Split it into scenes.'))}updateList();updateEditor();status(`${tr('audioReady')}: ${s.audio.duration.toFixed(1)}s`,1)});
async function useVoiceBlob(blob,name){const s=scene();if(!s)return;s.audio=await audioCtx().decodeAudioData(await blob.arrayBuffer());s.audioSource=name||'RECORDING';if($('audioFit').checked)s.duration=Math.min(120,Math.max(s.duration,s.audio.duration+.4));updateList();updateEditor();status(tr('audioReady'),1)}$('voiceUploadBtn').onclick=()=>$('voiceInput').click();$('voiceInput').onchange=async()=>{const f=$('voiceInput').files[0];if(f)try{if(f.size>maxFile)throw new Error('Audio file exceeds 50 MB');await useVoiceBlob(f,f.name)}catch(e){fail(e)}$('voiceInput').value=''};
$('recordBtn').onclick=async()=>{if(recording){recording.recorder.stop();return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){status(message('此瀏覽器無法錄音，請上傳音檔。','Microphone recording is unavailable; upload an audio file.'));return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const recorder=new MediaRecorder(stream);recordingChunks=[];const recordingScene=scene();recording={recorder,stream,sceneId:recordingScene.id};recorder.ondataavailable=e=>{if(e.data.size)recordingChunks.push(e.data)};recorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());recording=null;$('recordBtn').textContent=tr('recordVoice');try{const target=scenes.find(s=>s.id===recordingScene.id);if(target){const buffer=await audioCtx().decodeAudioData(await new Blob(recordingChunks,{type:recorder.mimeType}).arrayBuffer());target.audio=buffer;target.audioSource='MIC';if($('audioFit').checked)target.duration=Math.min(120,Math.max(target.duration,buffer.duration+.4));updateList();updateEditor();status(tr('audioReady'))}}catch(e){fail(e)}};recorder.start();$('recordBtn').textContent=tr('stopRecording');status(tr('recording'));setTimeout(()=>{if(recording?.recorder===recorder&&recorder.state==='recording')recorder.stop()},120000)}catch(e){fail(e)}};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}
function bufferWav(b){if(b.numberOfChannels===1)return wavBlob({audio:b.getChannelData(0),sampleRate:b.sampleRate});const mono=new Float32Array(b.length);for(let c=0;c<b.numberOfChannels;c++){const samples=b.getChannelData(c);for(let i=0;i<mono.length;i++)mono[i]+=samples[i]/b.numberOfChannels}return wavBlob({audio:mono,sampleRate:b.sampleRate})}
$('downloadVoice').onclick=()=>{const s=scene();if(s?.audio)download(bufferWav(s.audio),`${s.name||'narration'}.wav`)};$('playVoice').onclick=()=>{pause();if(!scene()?.audio)return;const c=audioCtx();c.resume();const src=c.createBufferSource();src.buffer=scene().audio;src.connect(c.destination);src.start();previewSources.push(src)};
function populateSystemVoices(){const list=window.speechSynthesis?.getVoices?.()||[];$('systemVoice').replaceChildren(...list.map((v,i)=>new Option(`${v.name} · ${v.lang}${v.localService?' · local':' · network'}`,String(i))));const i=list.findIndex(v=>v.lang.startsWith(lang.split('-')[0]));if(i>=0)$('systemVoice').value=String(i)}if(window.speechSynthesis){window.speechSynthesis.addEventListener('voiceschanged',populateSystemVoices)}$('speechBtn').onclick=()=>{if(!window.speechSynthesis)return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(scene()?.narration||'');utterance.voice=window.speechSynthesis.getVoices()[Number($('systemVoice').value)]||null;utterance.rate=Number($('voiceRate').value);window.speechSynthesis.speak(utterance)};
function ambient(){const c=audioCtx(),rate=22050,length=12,b=c.createBuffer(1,rate*length,rate),data=b.getChannelData(0);const freqs=[130.81,164.81,196];for(let i=0;i<data.length;i++){const time=i/rate;let v=0;for(let j=0;j<freqs.length;j++)v+=Math.sin(2*Math.PI*freqs[j]*time)*(0.4+.15*Math.sin(2*Math.PI*time/6+j))*0.085;const fade=Math.min(1,time/.4,(length-time)/.4);data[i]=v*Math.max(0,fade)}return b}let ambientBuffer=null;function getMusicBuffer(){return $('musicMode').value==='ambient'?(ambientBuffer||=ambient()):$('musicMode').value==='upload'?musicBuffer:null}
$('musicBtn').onclick=()=>$('musicInput').click();$('musicInput').onchange=async()=>{const f=$('musicInput').files[0];if(f)try{if(f.size>maxFile)throw new Error('Music file exceeds 50 MB');musicBuffer=await audioCtx().decodeAudioData(await f.arrayBuffer());musicFileName=f.name;$('musicMode').value='upload';$('musicName').textContent=`${f.name} · ${musicBuffer.duration.toFixed(1)}s`}catch(e){fail(e)}$('musicInput').value=''};$('musicMode').onchange=()=>{pause();$('musicName').textContent=$('musicMode').value==='upload'?musicFileName:$('musicMode').value==='ambient'?'Original procedural C major · 12s loop':''};$('musicVolume').oninput=()=>{if(playing)pause()};
$('srtBtn').onclick=()=>download(new Blob([subtitles(scenes,'srt')],{type:'text/plain;charset=utf-8'}),'FRAME-subtitles.srt');
$('exportBtn').onclick=()=>task(tr('export'),async signal=>{ai?.releaseModels?.();disposeDetector();await prepareVisualAssets(scenes);const tracks=scenes.filter(s=>s.audio&&(s.audioSource!=='VIDEO'||$('originalAudio').checked)).map(s=>({sceneId:s.id,buffer:s.audio,offset:0,volume:1}));if($('originalAudio').checked)for(const s of scenes)if(s.originalAudio&&s.audioSource!=='VIDEO')tracks.push({sceneId:s.id,buffer:sliceAudio(s.originalAudio,s.trimStart,s.trimEnd??s.originalAudio.duration),offset:0,volume:.35});if($('audioFit').checked){const fitted=fitAudioDurations(scenes,tracks);scenes=fitted.scenes;updateList()}if(document.fonts)await document.fonts.load('16px "FRAME CJK"','聰動成長協會');const caps=getExportCapabilities(settings());if(!caps.supported)throw new Error(caps.reason||caps.error||'MediaRecorder/captureStream unsupported');status(message('正在即時錄製影片。請保持此分頁在前景，不要鎖定螢幕。','Recording in real time. Keep this tab in the foreground and the screen unlocked.'),.01);const mb=getMusicBuffer();const result=await exportVideo({scenes,settings:settings(),audioTracks:tracks,music:mb?{buffer:mb,volume:Number($('musicVolume').value),start:0}:null,onProgress:p=>{let n=typeof p==='number'?p:p.progress??0;status(message('正在錄製，請保持分頁在前景…','Recording; keep the tab in the foreground…'),n>1?n/100:n)},signal});clearResult();resultUrl=URL.createObjectURL(result.blob);$('downloadVideo').href=resultUrl;$('downloadVideo').download=`FRAME-story-${Date.now()}.${result.extension}`;$('resultVideo').src=resultUrl;$('result').style.display='block';status(`${result.width}×${result.height} · ${result.duration.toFixed(1)}s · ${(result.blob.size/1024/1024).toFixed(1)} MB · ${result.mime}${result.warnings?.length?'\n'+result.warnings.join('\n'):''}`,1)});
$('cancelBtn').onclick=()=>{abort?.abort();disposeDetector();};
$('saveBtn').onclick=()=>task(tr('saveProject'),async()=>{const items=[];for(const s of scenes){const {image,video,audio,originalAudio,thumbnail,...rest}=s;items.push({...rest,audioData:audio?await dataUrl(bufferWav(audio)):null,originalAudioData:originalAudio?await dataUrl(bufferWav(originalAudio)):null})}const projectDocument={format:'FRAME-STORY',version:1,created:new Date().toISOString(),language:lang,scenes:items,output:settings(),music:musicBuffer?{name:musicFileName,data:await dataUrl(bufferWav(musicBuffer))}:null,musicMode:$('musicMode').value};const blob=new Blob([JSON.stringify(projectDocument)],{type:'application/json'});if(blob.size>maxProject)throw new Error('Project exceeds 150 MB. Use shorter media.');download(blob,'FRAME-story-project.json');status(tr('saved'),1)});
// Project files contain data only. Never restore runtime objects from user JSON.
function projectNumber(value,fallback,min,max){const n=Number(value);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback;}
function projectScene(row){
 if(!row||typeof row!=='object'||Array.isArray(row)||typeof row.mediaData!=='string'||!/^data:(image|video)\//i.test(row.mediaData))throw new Error('Project media must be embedded image/video data.');
 const s=baseScene(String(row.name||'Scene').slice(0,80));
 s.mediaData=row.mediaData;s.mediaType=row.mediaType==='video'?'video':'image';
 if(!s.mediaData.toLowerCase().startsWith('data:'+s.mediaType+'/'))throw new Error('Project media type does not match its embedded data.');
 s.visual=sanitizeVisual(row.visual);s.duration=projectNumber(row.duration,5,1,120);
 s.narration=String(row.narration||'').slice(0,1600);s.subtitle=String(row.subtitle||'').slice(0,1600);
 s.motion=['still','zoom-in','zoom-out','pan-left','pan-right'].includes(row.motion)?row.motion:'zoom-in';
 s.transition=['cut','fade','slide'].includes(row.transition)?row.transition:'fade';
 s.transitionDuration=projectNumber(row.transitionDuration,.5,0,2);
 for(const k of ['brightness','contrast','saturation'])s[k]=projectNumber(row[k],1,k==='saturation'?0:.2,3);
 s.warmth=projectNumber(row.warmth,0,-1,1);s.trimStart=projectNumber(row.trimStart,0,0,600);s.trimEnd=row.trimEnd==null?null:projectNumber(row.trimEnd,120,.1,600);
 s.audioSource=String(row.audioSource||'').slice(0,160);
 s.objects=(Array.isArray(row.objects)?row.objects:[]).slice(0,20).filter(o=>o&&typeof o==='object'&&typeof o.label==='string').map(o=>({label:o.label.slice(0,80),score:projectNumber(o.score,0,0,1),...(Array.isArray(o.bbox)&&o.bbox.length===4?{bbox:o.bbox.map(n=>projectNumber(n,0,0,100000))}:{})}));
 return s;
}
$('openBtn').onclick=()=>$('projectInput').click();
$('projectInput').onchange=()=>{
 const f=$('projectInput').files[0];$('projectInput').value='';if(!f)return;
 task(tr('openProject'),async signal=>{
  if(f.size>maxProject)throw new Error('Project exceeds 150 MB');
  const p=JSON.parse(await f.text());
  if(!p||p.format!=='FRAME-STORY'||p.version!==1||!Array.isArray(p.scenes)||p.scenes.length>maxScenes)throw new Error('Invalid FRAME project');
  for(const row of p.scenes){
   if(!row||typeof row!=='object'||Array.isArray(row))throw new Error('Invalid project scene');
   if(row.audioData&&(typeof row.audioData!=='string'||!/^data:audio\//i.test(row.audioData)))throw new Error('Project narration must be embedded audio data.');
   if(row.originalAudioData&&(typeof row.originalAudioData!=='string'||!/^data:audio\//i.test(row.originalAudioData)))throw new Error('Project original audio must be embedded audio data.');
  }
  if(p.music&&(typeof p.music!=='object'||typeof p.music.data!=='string'||!/^data:audio\//i.test(p.music.data)))throw new Error('Project music must be embedded audio data.');
  const incoming=[];let bytes=0;
  for(const row of p.scenes){
   if(signal.aborted)throw new DOMException('Cancelled','AbortError');
   const s=projectScene(row);bytes+=s.mediaData.length*.75;
   if(bytes>(smallDevice?32:150)*1024*1024)throw new Error('Project media exceeds this device budget. Compress assets or split the project.');
   if(s.mediaType==='video'){
    s.video=await videoFrom(s.mediaData);
    if(!Number.isFinite(s.video.duration)||s.video.duration<=0)throw new Error('Invalid project video duration');
    const c=document.createElement('canvas');c.width=180;c.height=100;c.getContext('2d').drawImage(s.video,0,0,c.width,c.height);s.thumbnail=c.toDataURL('image/jpeg',.7);
    s.trimStart=Math.max(0,Math.min(s.video.duration-.1,s.trimStart));s.trimEnd=Math.min(s.video.duration,Math.max(s.trimStart+.1,s.trimEnd??s.video.duration));
   }else{
    s.image=await imageFrom(s.mediaData);const limit=smallDevice?1280:2048;
    if(Math.max(s.image.naturalWidth,s.image.naturalHeight)>limit){const ratio=limit/Math.max(s.image.naturalWidth,s.image.naturalHeight),c=document.createElement('canvas');c.width=Math.max(1,Math.round(s.image.naturalWidth*ratio));c.height=Math.max(1,Math.round(s.image.naturalHeight*ratio));c.getContext('2d').drawImage(s.image,0,0,c.width,c.height);s.mediaData=c.toDataURL('image/jpeg',.9);s.image=await imageFrom(s.mediaData)}
    if(s.image.naturalWidth*s.image.naturalHeight+incoming.reduce((n,item)=>n+(item.image?item.image.naturalWidth*item.image.naturalHeight:0),0)>(smallDevice?12000000:40000000))throw new Error('Project photos exceed this device pixel budget. Open on a larger device or split the project.');
    s.thumbnail=s.mediaData;
   }
   if(row.audioData)s.audio=await audioCtx().decodeAudioData(await (await fetch(row.audioData)).arrayBuffer());
   if(row.originalAudioData)s.originalAudio=await audioCtx().decodeAudioData(await (await fetch(row.originalAudioData)).arrayBuffer());
   incoming.push(s);
  }
  const nextMusic=p.music?await audioCtx().decodeAudioData(await (await fetch(p.music.data)).arrayBuffer()):null;
  await prepareVisualAssets(incoming);if(signal.aborted)throw new DOMException('Cancelled','AbortError');
  scenes.forEach(s=>s.video?.pause());scenes=incoming;selected=0;time=0;
  musicBuffer=nextMusic;musicFileName=p.music?String(p.music.name||'Music').slice(0,160):'';$('musicName').textContent=musicFileName;
  $('musicMode').value=['none','ambient','upload'].includes(p.musicMode)?p.musicMode:'none';if($('musicMode').value==='upload'&&!musicBuffer)$('musicMode').value='none';
  if(p.output&&typeof p.output==='object'){
   const h=Number(p.output.height);$('resolution').value=[360,540,720].includes(h)?String(h):'540';$('fps').value=[12,24,30].includes(p.output.fps)?String(p.output.fps):'24';
   $('aspect').value=p.output.width<p.output.height?'portrait':p.output.width===p.output.height?'square':'landscape';$('captions').checked=!!p.output.subtitle;
   $('musicVolume').value=String(projectNumber(p.output.musicVolume,.15,0,1));$('format').value=['auto','mp4','webm'].includes(p.output.format)?p.output.format:'auto';$('audioFit').checked=p.output.fitNarration!==false;$('originalAudio').checked=p.output.originalAudio!==false;
  }
  updateList();updateEditor();status(tr('projectLoaded'),1);
 });
};
$('locateBtn').onclick=()=>{if(!navigator.geolocation){status(tr('unavailable'));return}const tab=window.open('about:blank','_blank');if(tab)tab.opener=null;navigator.geolocation.getCurrentPosition(p=>{const href=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.coords.latitude+','+p.coords.longitude)}`;if(tab)tab.location.href=href;else{status(href);const a=document.createElement('a');a.href=href;a.target='_blank';a.rel='noopener';a.textContent=tr('openMaps');$('status').append(a)}},e=>{tab?.close();status(`${tr('location')}: ${e.message}`)},{enableHighAccuracy:false,timeout:10000,maximumAge:300000})};
$('clearCacheBtn').onclick=async()=>{if(!globalThis.caches)return;for(const key of await caches.keys())if(key.startsWith('frame-story-'))await caches.delete(key);$('offlineInfo').textContent='';status(message('離線快取已清除；下次使用將重新讀取模型。','Offline cache cleared. Models will be read again next time.'));};
$('offlineBtn').onclick=()=>task(tr('offline'),async signal=>{if(location.protocol==='file:')throw new Error('Use localhost or HTTPS');if(!navigator.serviceWorker)throw new Error('Service Workers are unavailable.');const reg=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{cleanup();reject(new Error('Offline service worker timed out. Reload on HTTPS/localhost and retry.'))},15000);const onAbort=()=>{cleanup();reject(new DOMException('Cancelled','AbortError'))};const cleanup=()=>{clearTimeout(timer);signal.removeEventListener('abort',onAbort)};signal.addEventListener('abort',onAbort,{once:true});navigator.serviceWorker.ready.then(value=>{cleanup();resolve(value)},error=>{cleanup();reject(error)})});if(!reg?.active)throw new Error('Service Workers are unavailable.');const channel=new MessageChannel(),jobId=uid();await new Promise((resolve,reject)=>{channel.port1.onmessage=e=>{if(e.data.type==='progress')status(`Offline cache: ${e.data.done}/${e.data.total}`,e.data.done/e.data.total);if(e.data.type==='complete'){channel.port1.close();$('offlineInfo').textContent=`${e.data.files} files · ${Math.round(e.data.bytes/1024/1024)} MB`;resolve()}if(e.data.type==='error'){channel.port1.close();reject(new Error(e.data.error))}};signal.addEventListener('abort',()=>{reg.active.postMessage({type:'CANCEL_CACHE',jobId});channel.port1.close();reject(new DOMException('Cancelled','AbortError'))},{once:true});reg.active.postMessage({type:'CACHE_MODELS',jobId},[channel.port2])});status(message('離線檔案已儲存。瀏覽器仍可能在空間不足時清除快取。','Offline files saved. Browsers may evict cached files under storage pressure.'),1)});
async function demo(){pause();scenes=[];const coast=globalThis.__FRAME_DEMO__||new URL('dist/assets/demo-coast.webp',document.baseURI).href;const picture=await imageFrom(coast);const c=document.createElement('canvas');c.width=picture.naturalWidth;c.height=picture.naturalHeight;c.getContext('2d').drawImage(picture,0,0);const data=c.toDataURL('image/jpeg',.88);const texts=lang.startsWith('zh')?['清晨，我們沿著海岸出發。海風為故事揭開第一頁。','在旅途中央，慢下腳步，發現一個值得珍藏的瞬間。','夕陽將回憶染上暖色。我們帶著新的故事，繼續前行。']:['At dawn, we began our journey along the coast. The sea breeze opened the first page.','Halfway through the journey, we slowed down and found a moment worth keeping.','The evening light warmed our memories. With a new story, we continued on.'];for(let i=0;i<3;i++){const s=baseScene(`Coast · ${i+1}`);s.image=picture;s.mediaData=data;s.thumbnail=data;s.narration=texts[i];s.subtitle=texts[i];s.motion=['zoom-in','pan-right','zoom-out'][i];s.warmth=i*.08;s.duration=5;s.transition=['cut','fade','slide'][i];scenes.push(s)}selected=0;time=0;$('musicMode').value='ambient';updateList();updateEditor();status(message('三幕示範使用同一張海岸照片。文字是編輯示範；配音請點「生成可匯出配音」。','Three demo scenes use the same coast photo. These are edited example texts; click Generate speech to create a narration track.'))}
$('demoBtn').onclick=()=>demo().catch(fail);
document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing)pause()});window.addEventListener('pagehide',()=>{pause();recording?.stream.getTracks().forEach(t=>t.stop());disposeDetector();audioContext?.close();for(const u of objectUrls)URL.revokeObjectURL(u)});
function startup(){const memory=navigator.deviceMemory||null,threads=navigator.hardwareConcurrency||null,mobile=matchMedia('(max-width:700px)').matches;if(mobile||(memory&&memory<=4)){$('resolution').value='360';$('fps').value='12'}$('deviceInfo').textContent=`${memory?memory+' GB · ':''}${threads?threads+' threads · ':''}${mobile?'360p / 12fps':'540p / 24fps'} · ${navigator.deviceMemory?'hint':'browser hint'}`;applyLanguage();status(message('加入圖片，編輯分鏡文字，生成配音，再免費匯出。圖片與音訊留在此裝置。','Add pictures, edit scene text, generate speech, then export free. Pictures and audio stay on this device.'));getAi().catch(e=>{$('voiceInfo').textContent=e.message;console.warn(e)});if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register(new URL('service-worker.js',document.baseURI),{scope:new URL('.',document.baseURI).pathname}).catch(e=>{$('offlineInfo').textContent=e.message});}
document.fonts?.load('16px "FRAME CJK"','聰動').then(()=>draw()).catch(()=>{});
expertUI=mountExpertUI({container:$('expertTools'),getScene:scene,addGenerated:async(blob,name)=>{await addFile(new File([blob],name+'.png',{type:'image/png'}));selected=scenes.length-1;updateList();updateEditor();},task,status,t:tr,isBusy:()=>busy});
visualUI=mountVisualTools({container:$('visualTools'),getScene:scene,onChange:({scene:s})=>{clearResult();if(s)$('motion').value=s.motion;drawAsync();},t:tr,getLanguage:()=>lang,isBusy:()=>busy});
advancedUI=mountAdvancedUI({container:$('advancedTools'),getScene:scene,addGenerated:async(blob,name,kind)=>{await addFile(new File([blob],name,{type:kind==='video'?'video/mp4':'image/png'}));selected=scenes.length-1;updateList();updateEditor();},applyNarration:text=>{const s=scene();if(s){s.narration=text;s.subtitle=text;clearResult();updateList();updateEditor();}},task,status,t:tr,getLanguage:()=>lang,isBusy:()=>busy});
try{startup();globalThis.__FRAME_READY__=true;}catch(e){$('bootError').classList.remove('hidden');$('bootError').textContent=e.message;console.error(e)}
// Deliberately exposes a read-only inspection interface for reproducible browser QA.
window.FRAME_STORY={get scenes(){return scenes},get settings(){return settings()},get time(){return time},get busy(){return busy}};
