/* Optional same-origin native CPU image editor. No cloud endpoint or token. */
export function mountExpertUI({container,getScene,addGenerated,task,status,t,isBusy}) {
  container.innerHTML=`<details><summary data-i18n="expertTitle"></summary><p class="hint" data-i18n="expertHint"></p>
  <p><a href="native_cpu/README.html" target="_blank" data-i18n="expertGuide"></a></p>
  <button id="expertCheck" data-i18n="expertCheck"></button><p id="expertInfo" class="hint" aria-live="polite"></p>
  <label data-i18n="expertModel"></label><select id="expertModel"><option value="sd-turbo">SD-Turbo · img2img</option><option value="instruct-pix2pix">InstructPix2Pix · instruction edit</option><option value="sd-inpaint">SD 1.5 · inpainting</option></select>
  <label data-i18n="expertPrompt"></label><textarea id="expertPrompt" maxlength="1000" placeholder="Change the jacket to a blue coat; keep the same person"></textarea>
  <div class="field-row"><div><label data-i18n="expertSteps"></label><input id="expertSteps" type="number" min="1" max="4" value="4"></div><div><label data-i18n="expertSeed"></label><input id="expertSeed" type="number" min="0" max="2147483647" value="42"></div></div>
  <label data-i18n="expertStrength"></label><input id="expertStrength" type="range" min="0.1" max="1" step="0.05" value="0.7">
  <div id="expertMaskBox" hidden><label data-i18n="expertMask"></label><canvas id="expertMaskCanvas" width="512" height="288" style="width:100%;touch-action:none;background:#151b22;border:1px solid #50636e" aria-label="Paint replacement mask"></canvas><p class="hint" data-i18n="expertMaskHint"></p><label data-i18n="expertBrush"></label><input id="expertBrush" type="range" min="5" max="100" value="30"><button id="expertClearMask" data-i18n="expertClearMask"></button></div>
  <button id="expertRun" class="primary" style="width:100%;margin-top:12px" data-i18n="expertRun"></button></details>`;
  const $=id=>container.querySelector('#'+id), mask=document.createElement('canvas'), overlay=document.createElement('canvas');
  let installed=new Set(), checked=false, sceneId=null, painted=false, drawing=false, currentJob=null;
  const local=location.protocol==='http:'&&['127.0.0.1','localhost','[::1]'].includes(location.hostname);
  function translate(){container.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=t(e.dataset.i18n));}
  function maskScene(){const s=getScene();if(!s?.image)return;const scale=Math.min(1,512/s.image.naturalWidth,512/s.image.naturalHeight);mask.width=Math.round(s.image.naturalWidth*scale);mask.height=Math.round(s.image.naturalHeight*scale);overlay.width=mask.width;overlay.height=mask.height;$('expertMaskCanvas').width=mask.width;$('expertMaskCanvas').height=mask.height;mask.getContext('2d').fillStyle='#000';mask.getContext('2d').fillRect(0,0,mask.width,mask.height);painted=false;drawMask();}
  function drawMask(){const s=getScene(),canvas=$('expertMaskCanvas'),ctx=canvas.getContext('2d');if(!s?.image||!ctx)return;ctx.drawImage(s.image,0,0,canvas.width,canvas.height);const o=overlay.getContext('2d');o.clearRect(0,0,overlay.width,overlay.height);o.drawImage(mask,0,0);o.globalCompositeOperation='source-in';o.fillStyle='#50e8c6';o.fillRect(0,0,overlay.width,overlay.height);o.globalCompositeOperation='source-over';/* black pixels also opaque, so build an alpha mask */const pixels=mask.getContext('2d').getImageData(0,0,mask.width,mask.height);for(let i=0;i<pixels.data.length;i+=4){const alpha=pixels.data[i];pixels.data[i]=80;pixels.data[i+1]=232;pixels.data[i+2]=198;pixels.data[i+3]=Math.round(alpha*.55)}o.putImageData(pixels,0,0);ctx.drawImage(overlay,0,0);}
  function paint(e){if(!drawing||isBusy())return;const c=$('expertMaskCanvas'),r=c.getBoundingClientRect(),x=(e.clientX-r.left)*c.width/r.width,y=(e.clientY-r.top)*c.height/r.height,ctx=mask.getContext('2d');ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x,y,Number($('expertBrush').value),0,Math.PI*2);ctx.fill();painted=true;drawMask();}
  $('expertMaskCanvas').onpointerdown=e=>{if(!getScene()?.image||isBusy())return;drawing=true;e.currentTarget.setPointerCapture?.(e.pointerId);paint(e)};
  $('expertMaskCanvas').onpointermove=paint;
  $('expertMaskCanvas').onpointerup=$('expertMaskCanvas').onpointercancel=()=>drawing=false;
  $('expertClearMask').onclick=()=>maskScene();
  $('expertModel').onchange=()=>{$('expertSteps').value=$('expertModel').value==='sd-turbo'?'4':'20';$('expertSteps').max=$('expertModel').value==='sd-turbo'?'4':'30';$('expertStrength').disabled=$('expertModel').value!=='sd-turbo';refresh()};
  async function json(url,options){const r=await fetch(url,options);let data;try{data=await r.json()}catch{throw new Error(t('expertUnavailable'))}if(!r.ok)throw new Error(data.error||data.detail||`HTTP ${r.status}`);return data}
  $('expertCheck').onclick=async()=>{if(!local)return;try{const result=await json('api/status');installed=new Set(result.models.filter(m=>m.installed).map(m=>m.id));checked=result.dependencies_ready!==false;$('expertInfo').textContent=result.models.map(m=>`${m.id}: ${t(m.installed?'expertReady':'expertMissing')}`).join('\n');refresh()}catch(e){checked=false;$('expertInfo').textContent=t('expertUnavailable')}};
  $('expertRun').onclick=()=>task(t('expertRun'),async signal=>{const s=getScene();if(!s?.image)throw new Error(t('expertNeedImage'));const expert=$('expertModel').value;if(expert==='sd-inpaint'&&!painted)throw new Error(t('expertNeedMask'));if(expert==='sd-turbo'&&Number($('expertSteps').value)*Number($('expertStrength').value)<1)throw new Error('SD-Turbo: steps × strength must be at least 1.');const prompt=$('expertPrompt').value.trim();if(!prompt)throw new Error(t('expertPrompt'));const form=new FormData();form.set('expert',expert);form.set('prompt',prompt);form.set('steps',$('expertSteps').value);form.set('seed',$('expertSeed').value);form.set('strength',$('expertStrength').value);form.set('image_guidance','1.5');form.set('guidance',expert==='sd-turbo'?'0':'7.5');const photo=document.createElement('canvas');photo.width=mask.width;photo.height=mask.height;photo.getContext('2d').drawImage(s.image,0,0,photo.width,photo.height);form.set('image',await new Promise(resolve=>photo.toBlob(resolve,'image/png')),'photo.png');if(expert==='sd-inpaint')form.set('mask',await new Promise(resolve=>mask.toBlob(resolve,'image/png')),'mask.png');
    const cancel=()=>{if(currentJob)fetch(`api/jobs/${encodeURIComponent(currentJob)}/cancel`,{method:'POST'}).catch(()=>{})};signal.addEventListener('abort',cancel,{once:true});
    try{const job=await json('api/jobs',{method:'POST',body:form,signal});currentJob=job.id;if(signal.aborted){cancel();throw new DOMException('Cancelled','AbortError')}status(t('expertBusy'),.05);let result=job;while(!['completed','succeeded','failed','cancelled'].includes(result.status)){await new Promise((resolve,reject)=>{let timer;const abort=()=>{clearTimeout(timer);reject(new DOMException('Cancelled','AbortError'))};timer=setTimeout(()=>{signal.removeEventListener('abort',abort);resolve()},1000);signal.addEventListener('abort',abort,{once:true});if(signal.aborted)abort()});result=await json(`api/jobs/${encodeURIComponent(job.id)}`,{signal});status(t('expertBusy'),Math.min(.95,(Number(result.progress)||10)/100))}if(result.status==='failed')throw new Error(result.error||'CPU inference failed');if(result.status==='cancelled')throw new DOMException('Cancelled','AbortError');const response=await fetch(`api/jobs/${encodeURIComponent(job.id)}/result.png`,{signal});if(!response.ok)throw new Error('Generated image not available');await addGenerated(await response.blob(),`${s.name} · ${expert}`);status(t('expertDone'),1)}finally{signal.removeEventListener('abort',cancel);currentJob=null;refresh()}
  });
  function refresh(){translate();const s=getScene();if(sceneId!==s?.id){sceneId=s?.id;maskScene()}$('expertMaskBox').hidden=$('expertModel').value!=='sd-inpaint';$('expertStrength').disabled=$('expertModel').value!=='sd-turbo'||isBusy();$('expertCheck').disabled=!local||isBusy();$('expertRun').disabled=!local||!s?.image||isBusy()||!checked||!installed.has($('expertModel').value);if(!local)$('expertInfo').textContent=t('expertLocalOnly')}
  refresh();return{refresh};
}
