import L10N from './locales.json';
import DEMO from '../dist/assets/demo-coast.webp';
import {parsePrompt} from './motion-core.mjs';
import {loadDetector,detectImage,disposeDetector,detectorReady} from './detector-client.mjs';
const $=id=>document.getElementById(id);
const store={get(k){try{return localStorage.getItem(k)}catch{return null}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
const mapLanguage=code=>{if(L10N[code])return code;const lower=String(code).toLowerCase();if(lower.startsWith('zh'))return /cn|sg|hans/.test(lower)?'zh-Hans':'zh-Hant';return Object.keys(L10N).find(k=>k.toLowerCase()===lower.split('-')[0])};
let lang=mapLanguage(document.documentElement.dataset.locale)||mapLanguage(store.get('frame-cpu-language'))||(navigator.languages||[navigator.language]).map(mapLanguage).find(Boolean)||'en';
let source=null,objects=[],regions=[],plan=null,manual=false,drag=null,sourceName='',loading=false,job=null,worker=null,workerUrl='',workerId=0,backend='',statusKey='ready',detailKey='',resultUrl='',renderCount=0,lastRenderMs=0,exportFrames=0;
const pending=new Map();let reusableFrameBuffer=null;
const t=k=>L10N[lang]?.[k]||L10N.en[k]||k;
const sleep=(ms,signal)=>new Promise((resolve,reject)=>{if(signal?.aborted){reject(new DOMException('Cancelled','AbortError'));return;}const timeout=setTimeout(done,ms);function done(){signal?.removeEventListener('abort',abort);resolve();}function abort(){clearTimeout(timeout);signal?.removeEventListener('abort',abort);reject(new DOMException('Cancelled','AbortError'));}signal?.addEventListener('abort',abort,{once:true});});
function translate(){document.documentElement.lang=lang;document.documentElement.dir=L10N[lang].dir;document.title='FRAME CPU — '+t('title');document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=t(el.dataset.i18n)});document.querySelectorAll('[data-placeholder]').forEach(el=>el.placeholder=t(el.dataset.placeholder));$('language').value=lang;showStatus(statusKey,detailKey);renderObjects();renderPlan();}
function showStatus(key='ready',detail=''){statusKey=key;detailKey=detail;$('statusText').textContent=t(key);$('statusDetail').textContent=detail?t(detail):'';$('statusDot').className='status-dot'+(job?' busy':'');}
function controls(){const busy=!!job||loading;for(const id of ['imageFile','demo','detect','manual','regionType','prompt','applyPrompt','duration','resolution','fps','aspect','reset','saveFrame'])$(id).disabled=busy||(!source&&!['imageFile','demo'].includes(id));document.querySelectorAll('[data-preset],#objectList button,#objectList input').forEach(el=>el.disabled=busy);$('preview').disabled=busy||!source;$('export').disabled=busy||!source;$('cancel').hidden=job?.type!=='detect';$('stop').hidden=!['preview','record'].includes(job?.type);$('progress').hidden=job?.type!=='record'&&job?.type!=='detect';$('statusDot').className='status-dot'+(busy?' busy':'');}
function showView(mode){$('sourceWrap').hidden=mode!=='source';$('outputCanvas').hidden=mode!=='motion';$('resultVideo').hidden=mode!=='result';if(mode!=='result')$('resultVideo').pause();$('sourceTab').classList.toggle('selected',mode==='source');$('motionTab').classList.toggle('selected',mode!=='source');$('stageBadge').textContent=t(mode==='source'?'source':mode==='result'?'done':'preview');}
function disposeMotion(error=new DOMException('Cancelled','AbortError')){worker?.terminate();worker=null;reusableFrameBuffer=null;if(workerUrl){URL.revokeObjectURL(workerUrl);workerUrl='';}for(const p of pending.values()){clearTimeout(p.timer);p.reject(error);}pending.clear();}
function ensureMotion(){if(worker)return;if(!window.Worker)throw Error(t('unsupported'));if(window.__FRAME_MOTION_WORKER__){workerUrl=URL.createObjectURL(new Blob([window.__FRAME_MOTION_WORKER__],{type:'text/javascript'}));worker=new Worker(workerUrl,{name:'frame-cpu-motion'});}else worker=new Worker(new URL('motion-worker.bundle.js',document.baseURI),{name:'frame-cpu-motion'});worker.onmessage=({data:m})=>{const p=pending.get(m.id);if(!p)return;pending.delete(m.id);clearTimeout(p.timer);m.error?p.reject(Error(m.error)):p.resolve(m);};worker.onerror=e=>disposeMotion(Error(e.message||t('error')));worker.onmessageerror=()=>disposeMotion(Error(t('error')));}
function motionRequest(message,transfer=[]){ensureMotion();return new Promise((resolve,reject)=>{const id=++workerId;const timer=setTimeout(()=>disposeMotion(Error(t('error'))),45000);pending.set(id,{resolve,reject,timer});try{worker.postMessage({...message,id},transfer);}catch(e){pending.delete(id);clearTimeout(timer);reject(e);}});}
async function initMotion(){disposeMotion();const data=new Uint8ClampedArray(source.data);await motionRequest({type:'init',source:{width:source.width,height:source.height,data}},[data.buffer]);}
function dimensions(){const short=Number($('resolution').value),ratio=$('aspect').value;return ratio==='9:16'?[short,Math.round(short*16/9/2)*2]:ratio==='1:1'?[short,short]:[Math.round(short*16/9/2)*2,short];}
async function draw(time,token){if(token?.controller.signal.aborted)throw new DOMException('Cancelled','AbortError');const [width,height]=dimensions();const buffer=reusableFrameBuffer;reusableFrameBuffer=null;const m=await motionRequest({type:'frame',plan,time,duration:Number($('duration').value),width,height,buffer},buffer?[buffer]:[]);if(token?.controller.signal.aborted||token&&job!==token)throw new DOMException('Cancelled','AbortError');const canvas=$('outputCanvas');if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}canvas.getContext('2d',{alpha:false}).putImageData(new ImageData(m.frame.data,width,height),0,0);reusableFrameBuffer=m.frame.data.buffer;renderCount++;lastRenderMs=m.renderMs;$('metrics').textContent=`${width} × ${height} · ${m.renderMs.toFixed(0)} ms/frame`;return m;}
function clearResult(){if(resultUrl)URL.revokeObjectURL(resultUrl);resultUrl='';$('download').hidden=true;$('download').removeAttribute('href');$('resultVideo').pause();$('resultVideo').removeAttribute('src');$('resultVideo').load();}
async function loadFile(file){if(job||loading)return;if(!file||file.size>20*1024**2||!['image/jpeg','image/png','image/webp'].includes(file.type)){showStatus('error','unsupported');return;}let image,url;loading=true;controls();try{
 url=URL.createObjectURL(file);image=new Image();image.src=url;await image.decode();if(image.naturalWidth*image.naturalHeight>40000000||!image.naturalWidth)throw Error(t('unsupported'));
 const scale=Math.min(1,960/Math.max(image.naturalWidth,image.naturalHeight));const width=Math.max(1,Math.round(image.naturalWidth*scale)),height=Math.max(1,Math.round(image.naturalHeight*scale));
 const canvas=$('sourceCanvas');canvas.width=width;canvas.height=height;const context=canvas.getContext('2d',{willReadFrequently:true,alpha:false});context.fillStyle='#fff';context.fillRect(0,0,width,height);context.drawImage(image,0,0,width,height);source=context.getImageData(0,0,width,height);sourceName=file.name;$('fileName').textContent=file.name;$('dimensions').textContent=`${image.naturalWidth} × ${image.naturalHeight} → ${width} × ${height}`;
 objects=[];regions=[];manual=false;drag=null;clearResult();$('overlayCanvas').width=width;$('overlayCanvas').height=height;$('sourceWrap').style.maxWidth=Math.round(650*width/height)+'px';showView('source');overlay();renderObjects();buildPlan();await initMotion();showStatus('ready');
 }catch(e){showStatus('error',e.message||'unsupported');}finally{if(url)URL.revokeObjectURL(url);image=null;loading=false;controls();}}
async function loadDemo(){try{const blob=await(await fetch(DEMO)).blob();await loadFile(new File([blob],'frame-coast-demo.webp',{type:'image/webp'}));}catch(e){showStatus('error',e.message);}}
function overlay(){const c=$('overlayCanvas'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);if(!source)return;ctx.lineWidth=Math.max(2,c.width/350);ctx.font=`${Math.max(11,c.width/75)}px system-ui`;for(const r of [...objects,...regions]){if(r.enabled===false)continue;const b=r.bbox;ctx.strokeStyle=r.manual?'#9de3b7':'#c4afff';ctx.strokeRect(...b);ctx.fillStyle=ctx.strokeStyle;ctx.fillText((r.manual?t(r.type):r.label)+(r.score?' '+Math.round(r.score*100)+'%':''),b[0]+4,Math.max(14,b[1]-5));}if(drag){ctx.setLineDash([8,5]);ctx.strokeStyle='#fff';ctx.strokeRect(drag.x,drag.y,drag.endX-drag.x,drag.endY-drag.y);ctx.setLineDash([]);}$('overlayCanvas').style.touchAction=manual?'none':'auto';$('overlayCanvas').style.cursor=manual?'crosshair':'default';$('manual').classList.toggle('active-draw',manual);}
function renderObjects(){$('objectList').replaceChildren();const all=[...objects,...regions];if(!all.length){const li=document.createElement('li');li.textContent=t('none');$('objectList').append(li);return;}for(const r of all){const li=document.createElement('li'),label=document.createElement('label'),checkbox=document.createElement('input'),text=document.createElement('span'),small=document.createElement('small'),del=document.createElement('button');checkbox.type='checkbox';checkbox.checked=r.enabled!==false;checkbox.onchange=()=>{r.enabled=checkbox.checked;overlay();buildPlan();};text.textContent=r.manual?t(r.type):r.label;small.textContent=r.manual?t('manualBox'):`${t('confidence')} ${Math.round(r.score*100)}%`;label.append(checkbox,text);li.append(label,small);del.className='text-button';del.textContent='×';del.setAttribute('aria-label',t('deleteRegion'));del.onclick=()=>{objects=objects.filter(o=>o!==r);regions=regions.filter(o=>o!==r);overlay();renderObjects();buildPlan();};li.append(del);$('objectList').append(li);}controls();}
function buildPlan(){if(!source)return;plan=parsePrompt($('prompt').value,objects.filter(o=>o.enabled!==false),{regions:regions.filter(r=>r.enabled!==false),sourceWidth:source.width,sourceHeight:source.height,maxRegions:8,seed:314159});renderPlan();}
function renderPlan(){$('planSummary').replaceChildren();if(!plan)return;const desc=document.createElement('div');const names={zoomIn:'zoom',zoomOut:'zoom',left:'pan',right:'pan',up:'pan',down:'pan',sway:'sway',bob:'sway',pulse:'sway',water:'ripple',rain:'rain',snow:'snow',animate:'sway'};desc.textContent=plan.recognized.map(k=>t(names[k]||k)).join(' · ')||t('unknownPrompt');$('planSummary').append(desc);if(plan.warnings.length||plan.unhandled.length){const p=document.createElement('div');p.className='warning';p.textContent=plan.unhandled.length?t('unsupported')+' · '+t('unknownPrompt'):t('manualHelp');$('planSummary').append(p);}if(plan.effects.some(e=>e.region)){const p=document.createElement('div');p.className='hint';p.textContent=t('limitations');$('planSummary').append(p);}}
function begin(type){if(job||loading||!source)return null;manual=false;drag=null;overlay();const token={type,controller:new AbortController(),recorder:null,stream:null};job=token;controls();return token;}
function finish(token,key='ready',detail=''){token.stream?.getTracks().forEach(track=>track.stop());if(job===token){job=null;controls();showStatus(key,detail);}}
function stop(key='cancel'){const token=job;if(!token)return;job=null;token.controller.abort();if(token.type==='detect')disposeDetector();else disposeMotion();if(token.recorder?.state!=='inactive')try{token.recorder.stop();}catch{}token.stream?.getTracks().forEach(track=>track.stop());controls();showStatus(key);}
function embeddedModel(){const embedded=window.__FRAME_EMBEDDED_MODEL__;if(!embedded)return undefined;const binary=atob(embedded.weights);const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return{modelTopology:embedded.json.modelTopology,weightSpecs:embedded.json.weightsManifest.flatMap(g=>g.weights),weightData:bytes.buffer};}
async function detect(){const token=begin('detect');if(!token)return;showStatus('detectBusy','loading');$('progress').removeAttribute('value');try{const meta=await loadDetector({signal:token.controller.signal,workerSource:window.__FRAME_DETECTOR_WORKER__,embeddedModel:detectorReady()?undefined:embeddedModel(),workerUrl:new URL('detector-worker.js',document.baseURI),modelUrl:new URL('model/coco-ssd-lite/model.json',document.baseURI).href,onProgress:()=>{if(job===token)showStatus('detectBusy','loading');}});backend=meta.backend;const found=await detectImage(source,{minScore:.45,maxObjects:8,signal:token.controller.signal});if(job!==token)return;objects=found.map((o,i)=>({...o,id:'object-'+i,label:o.label||o.class,enabled:true,normalized:false}));overlay();renderObjects();buildPlan();finish(token,'ready',objects.length?'detectedBox':'none');}catch(e){if(job!==token)return;finish(token,e.name==='AbortError'?'cancel':'detectFailed',e.name==='AbortError'?'':e.message);}}
async function preview(){const token=begin('preview');if(!token)return;buildPlan();showView('motion');showStatus('preview');try{await initMotion();const began=performance.now(),duration=Number($('duration').value),fps=Number($('fps').value);while(job===token&&!token.controller.signal.aborted){const start=performance.now(),time=((start-began)/1000)%duration;await draw(time,token);await sleep(Math.max(0,1000/fps-(performance.now()-start)),token.controller.signal);}}catch(e){if(job===token)finish(token,e.name==='AbortError'?'cancel':'error',e.name==='AbortError'?'':e.message);}}
function recordingMime(){if(typeof MediaRecorder==='undefined')return'';for(const type of ['video/webm;codecs=vp8','video/webm;codecs=vp9','video/mp4;codecs=avc1.42E01E','video/mp4','video/webm'])if(MediaRecorder.isTypeSupported(type))return type;return'';}
async function exportVideo(){if(!recordingMime()||!HTMLCanvasElement.prototype.captureStream){showStatus('error','noRecorder');return;}const token=begin('record');if(!token)return;clearResult();buildPlan();showView('motion');showStatus('recording');$('progress').value=0;exportFrames=0;try{
 await initMotion();const first=await draw(0,token);const requested=Number($('fps').value),fps=Math.max(6,Math.min(requested,Math.floor(700/Math.max(1,first.renderMs))));const duration=Number($('duration').value);token.stream=$('outputCanvas').captureStream(fps);
 const mime=recordingMime(),chunks=[];token.recorder=new MediaRecorder(token.stream,{mimeType:mime,videoBitsPerSecond:Number($('resolution').value)===720?2500000:1400000});const recorder=token.recorder;
 const stopped=new Promise((resolve,reject)=>{recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=resolve;recorder.onerror=e=>reject(e.error||Error(t('error')));});stopped.catch(()=>{});recorder.start(500);
 const began=performance.now();while(job===token&&!token.controller.signal.aborted){const started=performance.now(),time=Math.min(duration,(started-began)/1000);await draw(time,token);exportFrames++;$('progress').value=Math.min(100,time/duration*100);if(time>=duration)break;await sleep(Math.max(0,1000/fps-(performance.now()-started)),token.controller.signal);}
 if(job!==token||token.controller.signal.aborted)throw new DOMException('Cancelled','AbortError');await sleep(1000/fps,token.controller.signal);recorder.stop();await stopped;if(job!==token)return;const actualMime=recorder.mimeType||mime,blob=new Blob(chunks,{type:actualMime});if(!blob.size)throw Error(t('noRecorder'));
 resultUrl=URL.createObjectURL(blob);const extension=/mp4/.test(actualMime)?'mp4':'webm';$('download').href=resultUrl;$('download').download='frame-cpu-photo-motion.'+extension;$('download').hidden=false;$('resultVideo').src=resultUrl;$('metrics').textContent=`${actualMime} · ${(blob.size/1024/1024).toFixed(2)} MB · ${exportFrames} frames`;showView('result');finish(token,'done');
 }catch(e){if(token.recorder?.state!=='inactive')try{token.recorder.stop();}catch{}if(job===token)finish(token,e.name==='AbortError'?'cancel':'error',e.name==='AbortError'?'':e.message);}finally{token.stream?.getTracks().forEach(track=>track.stop());}}
function point(event){const rect=$('overlayCanvas').getBoundingClientRect();return{x:Math.max(0,Math.min(source.width,(event.clientX-rect.left)*source.width/rect.width)),y:Math.max(0,Math.min(source.height,(event.clientY-rect.top)*source.height/rect.height))};}
function saveFrame(){if(!source||job||loading)return;let canvas=$('sourceWrap').hidden?$('outputCanvas'):$('sourceCanvas');const video=$('resultVideo');if(!video.hidden&&video.readyState>=2){canvas=document.createElement('canvas');canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0);}canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='frame-photo.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);},'image/png');}
Object.entries(L10N).forEach(([code,dict])=>$('language').add(new Option(dict.nativeName,code)));
$('language').onchange=()=>{lang=$('language').value;store.set('frame-cpu-language',lang);translate();};$('imageFile').onchange=e=>loadFile(e.target.files[0]);$('demo').onclick=loadDemo;$('detect').onclick=detect;$('applyPrompt').onclick=()=>{buildPlan();showStatus('ready');};$('preview').onclick=preview;$('export').onclick=exportVideo;$('stop').onclick=()=>stop();$('cancel').onclick=()=>stop();$('sourceTab').onclick=()=>{if(job)return;showView('source');};$('motionTab').onclick=()=>{if(job)return;if(resultUrl)showView('result');else preview();};$('saveFrame').onclick=saveFrame;$('reset').onclick=()=>{if(job)return;objects=[];regions=[];$('prompt').value='';clearResult();buildPlan();overlay();renderObjects();showView('source');showStatus('ready');};
$('manual').onclick=()=>{if(job||loading||!source)return;manual=!manual;drag=null;showView('source');overlay();showStatus('manual','manualHelp');if(manual&&matchMedia('(max-width:760px)').matches)$('stage').scrollIntoView({block:'center'});};
const oc=$('overlayCanvas');oc.onpointerdown=e=>{if(!manual||job||loading||!source||drag)return;e.preventDefault();oc.setPointerCapture(e.pointerId);const p=point(e);drag={...p,endX:p.x,endY:p.y,pointer:e.pointerId};};oc.onpointermove=e=>{if(!drag||drag.pointer!==e.pointerId||job||!manual)return;e.preventDefault();const p=point(e);drag.endX=p.x;drag.endY=p.y;overlay();};oc.onpointerup=e=>{if(!drag||drag.pointer!==e.pointerId||job||!manual)return;const x=Math.min(drag.x,drag.endX),y=Math.min(drag.y,drag.endY),width=Math.abs(drag.endX-drag.x),height=Math.abs(drag.endY-drag.y);if(width>=8&&height>=8&&regions.length<8)regions.push({id:'manual-'+Date.now(),type:$('regionType').value,bbox:[x,y,width,height],manual:true,enabled:true,normalized:false});drag=null;manual=false;overlay();renderObjects();buildPlan();showStatus('ready');};oc.onpointercancel=e=>{if(drag?.pointer!==e.pointerId)return;drag=null;overlay();};
const presets={zoom:'zoom in',pan:'pan right',sway:'animate sway',ripple:'water ripple',snow:'snow'};document.querySelectorAll('[data-preset]').forEach(button=>button.onclick=()=>{$('prompt').value=[$('prompt').value.trim(),presets[button.dataset.preset]].filter(Boolean).join('; ');buildPlan();});
const dz=$('dropzone');dz.ondragover=e=>{e.preventDefault();if(!job)dz.classList.add('drag');};dz.ondragleave=()=>dz.classList.remove('drag');dz.ondrop=e=>{e.preventDefault();dz.classList.remove('drag');if(!job)loadFile(e.dataTransfer.files[0]);};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&job)stop('hiddenPause');});window.addEventListener('pagehide',()=>{stop();disposeMotion();disposeDetector();clearResult();});
window.FRAME_CPU_DIAGNOSTICS=()=>({job:job?.type||null,detectorReady:detectorReady(),backend,objectsCount:objects.length,manualCount:regions.length,motionWorker:!!worker,pendingFrames:pending.size,renderCount,lastRenderMs,exportFrames,modelEmbedded:!!window.__FRAME_EMBEDDED_MODEL__,rules:plan?.recognized||[],effectCount:plan?.effects.length||0});
if((navigator.hardwareConcurrency||4)<4)$('fps').value='12';translate();controls();loadDemo();
